name: Get Http Package Repo

on:
  repository_dispatch:
  workflow_dispatch:
  
jobs:
  build:   # update build
    runs-on: ubuntu-latest  
    
    steps:
    
    - name: Checkout master branch
      uses: actions/checkout@v4
      with:
        ref: master
        
    - name: Set SSH key and known_hosts
      # appleboy/ssh-action@master  
      uses: webfactory/ssh-agent@v0.9.0     
      with:
        ssh-private-key: ${{ secrets.PERSONAL_SSH_KEY }}  

    - name: Setup git config
      run: |
        git config --global user.name "lysgwl"
        git config --global user.email "lysgwl@163.com"
        
    - name: Get and merge repository contents    