name: Sync Package Repo

on:
  schedule:
    - cron: '0 0 * * 0'
    # 每5分钟运行一次 (cron: '*/5 * * * *')
    # 每天凌晨运行 (0 0 * * *) 
    # 每周执行一次 (0 0 * * 0)
    # 每15天执行 (0 0 */15 * *)

#on:
#  repository_dispatch:
#  workflow_dispatch:

jobs:
  repo-sync:    # repo-sync
    runs-on: ubuntu-latest
    
    steps:
  
    - name: Checkout dest repository
      uses: actions/checkout@v4
      with:
        repository: 'lysgwl/openwrt-package'
        path: 'dest_repo'
        fetch-depth: 0

    - name: Checkout shidahuilang repository
      uses: actions/checkout@v4
      with:
        repository: 'shidahuilang/openwrt-package'
        path: 'src_repo'
        fetch-depth: 0
        
    - name: Set SSH key and known_hosts
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.PERSONAL_SSH_KEY }} 

    - name: Setup git config
      run: |
        git config --global user.name "lysgwl"
        git config --global user.email "lysgwl@163.com"     
    
    - name: Sync directories repository
      run: |
        rsync -a --delete src_repo/ dest_repo/shidahuilang/ --exclude .git
        
    - name: Commit and push repository using SSH
      run: |
        function check_git_commit {
            # 目标目录路径
            local target_path=$1 
            
            # 进入目标目录
            cd "$target_path" || { echo "Error: Unable to change directory to $target_path"; exit 1; }
            
            # 将所有变更添加到暂存区
            git add .
            
            # 输出git状态
            git status
            
            # 检查git状态
            local has_changes=$(git status --porcelain | grep '^[MADRC]')
            if [ -n "$has_changes" ]; then
                current_date=$(date '+%Y-%m-%d')
                
                git commit -a -m "commit repository  changes on current_date$"
                git push git@github.com:lysgwl/openwrt-package.git HEAD:master
            fi
            
            # 递归检查子目录的git状态
            for subdir in */; do
                if [ -d "$subdir" ]; then
                    check_git_commit "$subdir"
                fi
            done
        }
        
        # 
        cd dest_repo

        # 相对于git顶层目录的路径
        package_path_rel="shidahuilang"
        check_git_commit $package_path_rel
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2  # main
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        retain_days: 0
        keep_minimum_runs: 0    
