name: Update Other Package Repo

#on:
#  schedule:
#    - cron: '*/2 * * * *'     # 每天凌晨运行 (0 0 * * *)

on:
  repository_dispatch:
  workflow_dispatch:
  
jobs:
  build:   # update build
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        ref: master
        
    - name: Set SSH key and known_hosts
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PERSONAL_SSH_KEY }}   

    - name: Setup Git Config
      run: |
        git config --global user.name "lysgwl"
        git config --global user.email "lysgwl@163.com"      
        
    - name: Add remote repository
      run: |
        function add_fetch_repo() {
          git remote add $1 https://github.com/$2.git || true
          git fetch $1
        }
        
        add_fetch_repo diskman lisaac/luci-app-diskman
        add_fetch_repo ddns-go sirpdboy/luci-app-ddns-go
        add_fetch_repo openAppFilter destan19/OpenAppFilter
        add_fetch_repo poweroff esirplayground/luci-app-poweroff
        add_fetch_repo socat chenmozhijin/luci-app-socat

    - name: Copy Repository Contents
      run: |
        function copy_repo_contents() {
          mkdir -p $3
          git checkout $1/master -- $2
          cp -a $2/. $3/
        }
        
        copy_repo_contents diskman luci-app-diskman ${GITHUB_WORKSPACE}/otherpackage/luci-app-diskman
        copy_repo_contents ddns-go luci-app-ddns-go ${GITHUB_WORKSPACE}/otherpackage/luci-app-ddns-go
        copy_repo_contents openAppFilter OpenAppFilter ${GITHUB_WORKSPACE}/otherpackage/OpenAppFilter
        copy_repo_contents poweroff luci-app-poweroff ${GITHUB_WORKSPACE}/otherpackage/luci-app-poweroff
        copy_repo_contents socat luci-app-socat ${GITHUB_WORKSPACE}/otherpackage/luci-app-socat

    - name: Commit and Push repository using SSH
      run: |
        current_date=$(date '+%Y-%m-%d')
        
        git add .
        git commit -a -m "Merge code repository on $current_date"
        
        # git push git@github.com:lysgwl/openwrt-package.git ${{ github.ref }}:master
        git push git@github.com:lysgwl/openwrt-package.git HEAD:master    
        
    #- name: Push changes repository
    #  uses: ad-m/github-push-action@master
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}   # PERSONAL_ACCESS_TOKEN
    #    branch: ${{ github.ref }}    # master