name: Update Repo Package

on:
  push:
    branches:
      - master      # 指定在对master分支进行push时触发
  schedule:
    - cron: '0 0 */3 * *'
    # 每5分钟运行一次 (cron: '*/5 * * * *')
    # 每天凌晨运行 (0 0 * * *) 
    # 每周执行一次 (0 0 * * 0)
    # 每15天执行 (0 0 */15 * *)
    # 每3天执行 (0 0 */3 * *)
  repository_dispatch:
  workflow_dispatch:
  
env:
  REPO_OTHER_COND: 1
  REPO_REMOTE_COND: 1
  SCRIPT_NAME: update_scripts.sh
  SYSTEM_DIR: system-utils
  SCRIPT_ROOT: ${{ github.workspace }}/.github/scripts
  SYSTEM_REPO: git@github.com:lysgwl/system-utils.git
  
jobs:
  build:   # update build repo-sync
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v7
      with:
        ref: master
        
    - name: Set SSH key and known_hosts
      uses: webfactory/ssh-agent@v0.10.0   # appleboy/ssh-action@master
      with:
        ssh-private-key: ${{ secrets.PERSONAL_SSH_KEY }}
        
    - name: Clone system-utils repository
      run: |
        echo "=== CLONE SYSTEM UTILS ==="
        
        SYSTEM_ROOT="${SCRIPT_ROOT}/${SYSTEM_DIR}"
        mkdir -p "$SCRIPT_ROOT"
        
        if [[ ! -d "${SYSTEM_ROOT}" ]]; then
            git clone \
                --depth 1 \
                --branch master \
                "${SYSTEM_REPO}" \
                "${SYSTEM_ROOT}"
        fi
        
        UPDATE_SCRIPT="${SCRIPT_ROOT}/${SCRIPT_NAME}"
        
        echo "SYSTEM_ROOT=${SYSTEM_ROOT}" >> "${GITHUB_ENV}"
        echo "UPDATE_SCRIPT=${UPDATE_SCRIPT}" >> "${GITHUB_ENV}"
        
    - name: Update other packages
      if: env.REPO_OTHER_COND != 0 && !cancelled()
      run: |
        echo "=== UPDATE OTHER REPOSITORIES ==="
        OTHER_PACKAGE_ROOT="${GITHUB_WORKSPACE}/otherpackage"
        
        if [[ ! -f "${UPDATE_SCRIPT}" ]]; then
            echo "[ERROR] 更新脚本不存在: ${UPDATE_SCRIPT}"
            exit 1
        fi
        
        source "${UPDATE_SCRIPT}"
        
        update_other_package "${OTHER_PACKAGE_ROOT}"
        ls -al "$OTHER_PACKAGE_ROOT"