name: Update Other Package Repo

#on:
#  schedule:
#    - cron: '*/5 * * * *'     # 每天凌晨运行 (0 0 * * *)

on:
  repository_dispatch:
  workflow_dispatch:
  
jobs:
  build:   # update
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        ref: master
        
    - name: Set SSH key and known_hosts
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PERSONAL_SSH_KEY }}    
        
    - name: Add remote repository
      run: |
        git remote add poweroff https://github.com/esirplayground/luci-app-poweroff.git || true
        
    - name: Fetch the latest code
      run: |
        git fetch poweroff
   
    - name: Merge code into specific directory
      run: |
        if [ ! -d "otherpackage" ]; then
            mkdir -p "otherpackage"
        fi

        git read-tree --prefix=otherpackage/luci-app-poweroff/ -u poweroff/master
        
    - name: Commit info to Git
      run: |
        git config --global user.name "lysgwl"
        git config --global user.email "lysgwl@163.com"
        
        current_date=$(date '+%Y-%m-%d')
        
        git add .
        git commit -a -m "Merge code repository on $current_date"

    #- name: Push changes repository
    #  uses: ad-m/github-push-action@master
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}   # PERSONAL_ACCESS_TOKEN
    #    branch: ${{ github.ref }}    # master
    
    - name: Push changes repository using SSH
      run: |
        # git push git@github.com:lysgwl/openwrt-package.git ${{ github.ref }}:master
        git push git@github.com:lysgwl/openwrt-package.git HEAD:master