name: Update Other Package Repo

on:
  push:
    branches:
      - master      # 指定在对master分支进行push时触发
  schedule:
    - cron: '0 0 */3 * *'
    # 每5分钟运行一次 (cron: '*/5 * * * *')
    # 每天凌晨运行 (0 0 * * *) 
    # 每周执行一次 (0 0 * * 0)
    # 每15天执行 (0 0 */15 * *)
    # 每3天执行 (0 0 */3 * *)
  repository_dispatch:
  workflow_dispatch:
  
env:
  BUILD_SCRIPT: run-scripts.sh
  REPO_OTHER_COND: 1
  REPO_REMOTE_COND: 1
  
jobs:
  build:   # update build repo-sync
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        # 设置脚本路径
        scripts_file="${GITHUB_WORKSPACE}/.github/scripts/${BUILD_SCRIPT}"
        
        # 验证脚本存在
        if [ ! -e "${scripts_file}" ]; then
            echo "::error file=${scripts_file}::Build script not found"
            exit 1
        fi

        # 设置可执行权限
        chmod +x "${scripts_file}"

        # 输出磁盘信息
        echo "Disk usage before operations:"
        df -hT

        # 设置环境变量
        echo "SCRIPT_PATH=${scripts_file}" >> $GITHUB_ENV
        echo "REPO_SSH_URL=git@github.com:${GITHUB_REPOSITORY}.git" >> $GITHUB_ENV

    - name: Set SSH key and known_hosts
      uses: webfactory/ssh-agent@v0.9.0   # appleboy/ssh-action@master
      with:
        ssh-private-key: ${{ secrets.PERSONAL_SSH_KEY }}

    - name: Setup git config
      run: |
        git config --global user.name "lysgwl"
        git config --global user.email "lysgwl@163.com"
        git config --global init.defaultBranch main

    - name: Get other repository contents
      if: env.REPO_OTHER_COND != 0 && !cancelled()
      run: |
        echo "=== SYNCING OTHER REPOSITORIES ==="
        mkdir -p "$PWD/otherpackage"
        source ${{ env.SCRIPT_PATH }}
        get_other_repo "$PWD/otherpackage"
        echo "::notice::Other repositories synced successfully"
        
    - name: Get remote repository contents
      if: env.REPO_REMOTE_COND != 0 && !cancelled()
      run: |
        echo "=== SYNCING REMOTE REPOSITORIES ==="
        mkdir -p "$PWD/remotepackage"
        source ${{ env.SCRIPT_PATH }}
        get_remote_repo "$PWD/remotepackage"
        echo "::notice::Remote repositories synced successfully"
    
    - name: Commit and push repository using SSH
      run: |
        echo "=== COMMITTING AND PUSHING CHANGES ==="
        source ${{ env.SCRIPT_PATH }}
        check_git_commit "${{ env.REPO_SSH_URL }}" "$PWD"
        echo "::notice::All changes committed and pushed"

    #- name: Push changes repository
    #  uses: ad-m/github-push-action@master
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}   # PERSONAL_ACCESS_TOKEN
    #    branch: ${{ github.ref }}    # master    
        
    - name: Delete workflow runs
      if: always()
      uses: Mattraks/delete-workflow-runs@v2  # main
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0          # 全部删除只留正在跑的一条
        keep_minimum_runs: 0    # 全部删除只留正在跑的一条
